name: maxwell_client
version: 0.10.1
description: A maxwell client for dart.
repository: https://github.com/maxwell-dev/maxwell-client-dart.git

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  logger: ^1.4.0
  time: ^2.1.3
  async: ^2.10.0
  meta: ^1.8.0
  tuple: ^2.0.2
  http: ^0.13.0
  fixnum: ^1.0.0
  web_socket_channel: ^2.4.0
  maxwell_protocol: ^0.7.1

dev_dependencies:
  test: ^1.24.3
