name: maxwell_client
version: 0.6.8
description: A maxwell client for dart.
homepage: https://github.com/maxwell-dev/maxwell-client-dart.git
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  logger: ^1.4.0
  time: ^2.1.3
  async: ^2.11.0
  meta: ^1.9.1
  tuple: ^2.0.2
  http: ^1.1.0
  web_socket_channel2:
    git:
      url: https://github.com/xuchaoqian/web_socket_channel2.git
      ref: v2.2.0+fork.2
  maxwell_protocol:
    git:
      url: https://github.com/maxwell-dev/maxwell-protocol-dart.git
      ref: v0.7.0

dev_dependencies:
  test: 1.24.3
