name: maxwell_client
version: 0.5.5
description: A maxwell client for dart.
homepage: https://github.com/maxwell-dev/maxwell-client-dart.git
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  logger: ^1.0.0
  time: ^1.2.0
  async: ^2.4.0
  meta: ^1.1.8
  tuple: ^1.0.3
  web_socket_channel2:
    git:
      url: https://github.com/xuchaoqian/web_socket_channel2.git
      ref: v2.2.0+fork.2
  maxwell_protocol:
    git:
      url: https://github.com/maxwell-dev/maxwell-protocol-dart.git
      ref: master

dev_dependencies:
  test: 1.21.0
